spring.application.name=ProductCatalog

spring.datasource.url=jdbc:postgresql://localhost:5432/Microservices
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.circuitbreaker.instances.catalogCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.catalogCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.catalogCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.catalogCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.catalogCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.catalogCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.catalogCB.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.catalogCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.catalogCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.catalogCB.recordExceptions=java.lang.Exception


management.endpoints.web.exposure.include=*